server:
  port: 8083

spring:
  application:
    name: location-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

uber:
  location:
    driver-ttl-seconds: ${LOCATION_DRIVER_TTL_SECONDS:60}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
